@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Conversation {
  - lines: List<Line>
  - id: String
  - conversationDate: LocalDate
  - createdOn: LocalDateTime
}
class Line {
  - punchLine: boolean
  - lineType: LineType
  - participants: List<Participant>
  - text: String
}
enum LineType << enumeration >> {
  + SPEECH: 
  + CONTEXT: 
}
class Participant {
  - victim: boolean
  - name: String
}

Conversation "1" *-[#595959,plain]-> "lines\n*" Line         
Line         "1" *-[#595959,plain]-> "lineType\n1" LineType     
Line         "1" *-[#595959,plain]-> "participants\n*" Participant  
@enduml
