import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // Shorthand: Just a string of the Doc ID
    'adr/index', 

    // Category for the rest of the ADRs
    {
      type: 'category',
      label: 'Decision Records',
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr', 
        },
      ],
    },
  ],
   
};

export default sidebars;
